### ISSUE TITLE
firmware binary for flsun qq-s

### ISSUE THREAD

**Issue by jpnielsen** [mukamuk1/klipper-config#1]
I can't figure out how to make firmware for my printer.

did you clone the latest klipper and "make flash" - or ?

I found an older firmware binary, https://github.com/berghauz/klipper/tree/mks-robin-support/precompiled/flsun_qq_s
but it doesn't work with the latest klipper

**Comment by jpnielsen** [comment]
Got it working now

`Build for the stm32f103 with a 28KiB bootloader. Comms on USART3. 

After building the image, run: ~/klipper/scripts/update_mks_robin.py out/klipper.bin robin_mini.bin. Then copy the robin_mini.bin file to the printer's SD card to flash it.`

https://github.com/KevinOConnor/klipper/issues/2397#issuecomment-603282594

**Comment by ddacunha** [comment]
I did copy the file to the SD card, but nothing happens. Printer is a Q5. 

```
$ ls -1
FQQ_xyzCalibration_cube.gcode
firstlayer.gcode
robin_mini.bin
```

Also, it says that I have version 2.4 of the firmware.

**Comment by mukamuk1** [comment]
This is firmware for QQ-S Pro not for Q5.

**Comment by ddacunha** [comment]
Thanks for the quick reply. Do you know how can I make the firmware for the Q5?

**Comment by mukamuk1** [comment]
https://github.com/KevinOConnor/klipper/blob/master/config/printer-flsun-q5-2020.cfg this is config for Q5 (it is included in vanilla klipper) and there is instructions for building fw for Q5

**Comment by ddacunha** [comment]
I didn't realise this, I have been searching the internet for hours :(
Thanks!
